### PR TITLE
Add issue template config

### PR DESCRIPTION
**Pull request by matthew-white**
Using the same config as the `central` repository. See getodk/central#216.

### CODE REVIEW

**Review by lognaturel — CHANGES_REQUESTED** [review]
We should update this based on https://github.com/getodk/central/pull/218

**Review by lognaturel — CHANGES_REQUESTED** [review]
No seriously, I want some changes.

**Review by lognaturel — CHANGES_REQUESTED** [review]
I EXTRA request changes.

(See @getodk/testers repeating review states can be helpful. 😉)

**Comment by matthew-white** [comment]
Just updated `config.yml` to reflect the latest. @lognaturel, this should be ready for another look!

**Review by lognaturel — APPROVED** [review]

**Pull request merged**
