### PR TITLE
Update link to user-facing docs

### PR DESCRIPTION
**Pull request by yanokwa**

### CODE REVIEW

**Review by matthew-white — APPROVED** [review]

**Comment by matthew-white** [comment]
@lognaturel, you mentioned possibly moving the pyODK docs to docs.getodk.org. Would that happen before .3 is released? If so, maybe we should hold off on merging this PR?

**Comment by yanokwa** [comment]
We could use `https://docs.getodk.org/pyodk` as the URL. That redirects now to Github and be the likely URL. What say ye, @lognaturel.

**Comment by matthew-white** [comment]
It looks like there's a conflict now that we've merged #784. The component was moved to src/components/odata/analyze.vue.

In terms of which link to use, either approach seems reasonable to me!

**Comment by yanokwa** [comment]
Fixed conflict and updated link to docs.getodk.org

**Review by matthew-white — APPROVED** [review]
Thanks, @yanokwa! I'll go ahead and merge now.

**Pull request merged**
