### PR TITLE
Remove ability to create backups config

### PR DESCRIPTION
**Pull request by matthew-white**
This PR:

- Removes the "Set up now" button and the corresponding modal.
- Updates text.

We may update the text again once we put out more messaging around a deprecation timeline. The text updates in this PR are what will go out with the patch release.

You can see the text changes by taking a look at the components. Text changed the most in the "backups are not configured" case and in the "Terminate Automatic Backups" modal, so I've also added screenshots of those below.

I'm tagging @lognaturel for a review of the text changes and @ktuite for a more general code review.

Screen Shot 2022-09-14 at 4 58 17 PM
Screen Shot 2022-09-14 at 4 56 58 PM

### CODE REVIEW

**Comment by matthew-white** [comment]
@ktuite, I think this can be reviewed async.

**Comment by lognaturel** [comment]
Behavior/wording looks great to me.

**Review by ktuite — APPROVED** [review]

**Comment by ktuite** [comment]
It looks like if they _do_ have backups turned on, there will be no message here about the feature going away, except in the "terminate" button modal. Do we want any sort of warning/alert in the status here about the feature being on a deprecation path?

**Review by ktuite — APPROVED** [review]
Looked again at latest commits (showing the deprecation alert when backups have been configured) and it looks good! 

Also tried it out.
Screen Shot 2022-09-20 at 5 21 34 PM

**Pull request merged**
