### PR TITLE
Make small changes to ProjectEnableEncryption

### PR DESCRIPTION
**Pull request by matthew-white**
Screenshot:

Screen Shot 2022-11-22 at 6 24 52 PM

### CODE REVIEW

**Comment by lognaturel** [comment]
Yay! Given that there's no string for finish, did you consider "Enable Encryption"? I guess you think "Finish" might get used elsewhere?

"there are no length restrictions" is a lie -- we now enforce 10 chars. Maybe fix that too while here? Fine if you'd rather separate out.

**Comment by matthew-white** [comment]
> Given that there's no string for finish, did you consider "Enable Encryption"? I guess you think "Finish" might get used elsewhere?

I wouldn't be surprised if "Finish" gets reused, but I'd also be happy to run with "Enable Encryption" if that seems better to you!

> "there are no length restrictions" is a lie -- we now enforce 10 chars. Maybe fix that too while here?

On it!

**Comment by lognaturel** [comment]
> wouldn't be surprised if "Finish" gets reused

Ok, let's do that for now!

**Comment by matthew-white** [comment]
Screen Shot 2022-11-22 at 6 33 04 PM

**Review by lognaturel — APPROVED** [review]

**Comment by lognaturel** [comment]
I noticed that the “First” also implies this is a multi step process. But I think these changes are enough for now.

**Pull request merged**
