### PR TITLE
Upgrade web-forms to v0.4

### PR DESCRIPTION
**Pull request by sadiqkhoja**
- Updated @getodk/web-forms version to 0.3.
- Removed box-shadow of the html body for web-forms preview

This PR is deployed to dev environment as well.

### CODE REVIEW

**Comment by matthew-white** [comment]
@sadiqkhoja, is this PR ready to be merged? We're planning to start regression testing tomorrow or Monday. Do you think it'd be possible to merge it before then? (No big deal if not.)

**Comment by lognaturel** [comment]
We want to do one more Web Forms release to get a couple more improvements in so maybe it’s not worth merging this one in. It would be great to get the new version today if possible. 

I think only https://github.com/getodk/web-forms/pull/216 is pending review and everything else is merged already. @sadiqkhoja does that sound right?

**Comment by sadiqkhoja** [comment]
Yes, that's right, I want to merge https://github.com/getodk/web-forms/pull/216 and release a new version before merging this PR. I should be able to do that today.

**Comment by sadiqkhoja** [comment]
I have updated the web-forms version to v0.4 and validated a Form with acknowledge/trigger question. I think we can now merge this.

**Review by lognaturel — APPROVED** [review]

**Pull request merged**
